#!/bin/bash
mcVersion="1.8"
echo "Initializing/Updating Git submodules"
git submodule update --init --recursive

echo "Compiling Java utility classes"

# javac won't run if the target doesn't exist as a directory
[ -f  ./workspace ] && rm ./workspace # delete if normal file
#[ -d  ./workspace ] && rm -r ./workspace # delete if directory, too
[ -d ./workspace ] || mkdir ./workspace # create if not exists
[ -f  ./workspace/java ] && rm ./workspace/java # delete if normal file
[ -d ./workspace/java ] || mkdir ./workspace/java # create if not exists

cd ./src/main/java # ./src/main/java/
# compile required utility classes
javac -d ../../../workspace/java \
./net/caseif/quartz/util/Downloader.java \
./net/caseif/quartz/util/Extractor.java \
./net/caseif/quartz/util/SrgSplicer.java
cd ../../../workspace/java/ # ./workspace/java/

# download vanilla server
java net.caseif.quartz.util.Downloader \
-u https://s3.amazonaws.com/Minecraft.Download/versions/$mcVersion/minecraft_server.$mcVersion.jar \
-o ../lib/minecraft_server-$mcVersion.jar \
-n "vanilla server" \
-ow

# download MCP
java net.caseif.quartz.util.Downloader \
-u https://www.dropbox.com/s/1xon92yn9w6kg3s/mcp910-pre1.zip?dl=1 \
-o ../lib/mcp.zip \
-n "MCP" \
-ow
# extract MCP
echo "Extracting deobfuscation mappings, please wait..."
java net.caseif.quartz.util.Extractor -i ../lib/mcp.zip -o ../lib/srg/joined.srg -e conf/joined.srg -ow
java net.caseif.quartz.util.Extractor -i ../lib/mcp.zip -o ../lib/srg/fields.csv -e conf/fields.csv -ow
java net.caseif.quartz.util.Extractor -i ../lib/mcp.zip -o ../lib/srg/methods.csv -e conf/methods.csv -ow

# splice CSVs with main SRG file
java net.caseif.quartz.util.SrgSplicer ../lib/srg/ ../lib/srg/notch-mcp.srg

# download SrgTool
java net.caseif.quartz.util.Downloader \
-u http://repo.caseif.net/content/groups/public/nl/hardijzer/fw/srgtool/srgtool/2.0/srgtool-2.0.jar \
-o ../lib/srgtool-2.0.jar \
-n "srgtool" \
-ow

cd ../ # ./workspace/

echo "Deobfuscating server"
java -jar ./lib/srgtool-2.0.jar apply --srg ./lib/srg/notch-mcp.srg --in ./lib/minecraft_server-1.8.jar --inheritance ./lib/minecraft_server-1.8.jar --out ./lib/minecraft_server-deobf-1.8.jar

echo "Done!"
